### ISSUE TITLE
Window not Defined

### ISSUE THREAD

**Issue by prbhanu** [alias-rahil/handwritten.js#73]
E:\handwriting>node index.js
E:\handwriting\node_modules\handwriting.js\index.js:14429
window.HandWriting = HandWriting;
^

ReferenceError: window is not defined
    at Object.<anonymous> ←[90m(E:\handwriting\←[39mnode_modules\←[4mhandwriting.js←[24m\index.js:14429:1←[90m)←[39m
    at __webpack_require__ ←[90m(E:\handwriting\←[39mnode_modules\←[4mhandwriting.js←[24m\index.js:20:30←[90m)←[39m
    at ←[90mE:\handwriting\←[39mnode_modules\←[4mhandwriting.js←[24m\index.js:66:18
    at Object.<anonymous> ←[90m(E:\handwriting\←[39mnode_modules\←[4mhandwriting.js←[24m\index.js:69:10←[90m)←[39m
←[90m    at Module._compile (node:internal/modules/cjs/loader:1275:14)←[39m
←[90m    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:1133:32)←[39m
←[90m    at Module._load (node:internal/modules/cjs/loader:972:12)←[39m
←[90m    at Module.require (node:internal/modules/cjs/loader:1157:19)←[39m
←[90m    at require (node:internal/modules/helpers:119:18)←[39m

Node.js v19.9.0

**Comment by alias-rahil** [comment]
`handwriting.js` is a different library. This repo is for `handwritten.js`
